### ISSUE TITLE
0.128.0-ext-alpine-ci seems to be missing autoprefixer, 0.127.0-ext-alpine-ci had it

### ISSUE THREAD

**Issue by mhansen** [floryn90/docker-hugo#120]
**Describe the bug**

On https://gitlab.com/graphviz/graphviz.gitlab.io/-/merge_requests/683, renovatebot proposed updating from 0.127.0-ext-alpine-ci to 0.128.0-ext-alpine-ci.

And our build breaks on the proposal. Our site is a docsy site.

```
$ hugo
hugo: downloading modules …
hugo: collected modules in 14463 ms
Start building sites … 
hugo v0.128.0-e6d2712ee062321dc2fc49e963597dd5a6157660+extended linux/amd64 BuildDate=2024-06-25T16:15:48Z VendorInfo=gohugoio
WARN  deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.Disqus.Shortname instead.
Total in 19694 ms
Error: error building site: POSTCSS: failed to transform "/scss/main.css" (text/css): Error: Loading PostCSS Plugin failed: Cannot find module 'autoprefixer'
Require stack:
- /tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/postcss.config.js
(@/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/postcss.config.js)
    at load (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/plugins.js:28:11)
    at async Promise.all (index 0)
    at async plugins (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/plugins.js:57:12)
    at async processResult (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/index.js:39:14)
    at async Promise.all (index 0)
```

My understanding is autoprefixer *should* be included in the image: https://github.com/floryn90/docker-hugo/blob/master/src/docker/alpine-ext/ext-alpine.df#L34

I'm not sure why it's not any more. Has something changed here recently?

**To Reproduce**

Try to import autoprefixer.

**Expected behavior**
It imports.

**Screenshots**
See logs above.

**Desktop (please complete the following information):**
GitLab linux CI environment.

**Additional context**
This isn't an urgent problem for us, or anything, we can just not merge this proposal yet, just thought I'd reach out upstream in case you know what happened.

**Comment by mhansen** [comment]
I should add there's a good chance we are doing something wrong here too. I haven't investigated deeply yet.

**Comment by mhansen** [comment]
Thank you!

**Comment by mhansen** [comment]
Hmm, our [merge request](https://gitlab.com/graphviz/graphviz.gitlab.io/-/merge_requests/683) has updated to `0.128.2-ext-alpine-ci`, which seems to include your latest fix https://github.com/floryn90/docker-hugo/releases/tag/v0.128.2, 

But I'm still getting the same error. Logs: 

```
Running with gitlab-runner 17.0.0~pre.88.g761ae5dd (761ae5dd)
  on green-6.saas-linux-small-amd64.runners-manager.gitlab.com/default YKxHNyexq, system ID: s_a[2](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L2)01ab37b78a
Resolving secrets
Preparing the "docker+machine" executor
00:18
Using Docker executor with image floryn90/hugo:0.128.2-ext-alpine-ci ...
Pulling docker image floryn90/hugo:0.128.2-ext-alpine-ci ...
Using docker image sha256:1b794749e1206f2afad19a491a950558d[3](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L3)27584d5ae9aab43516[4](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L4)1580eeaf10b for floryn90/hugo:0.128.2-ext-alpine-ci with digest floryn90/hugo@sha2[5](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L5)6:5075a37159ad14b93ba3c945eb0f40e57d739eb59a75c4159c17e7a5bc108e8f ...
Preparing environment
00:0[6](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L6)
Running on runner-ykxhnyexq-project-4212598-concurrent-0 via runner-ykxhnyexq-s-l-s-amd64-1[7](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L7)20170392-70c4a56f...
Getting source from Git repository
00:08
Fetching changes...
Initialized empty Git repository in /builds/graphviz/graphviz.gitlab.io/.git/
Created fresh repository.
Checking out 7a6c9333 as detached HEAD (ref is renovate/floryn90-hugo-0.x)...
Skipping Git submodules setup
$ git remote set-url origin "${CI_REPOSITORY_URL}"
Executing "step_script" stage of the job script
00:24
Using docker image sha256:1b794749e1206f2afad19a491a95055[8](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L8)d327584d5ae9aab4351641580eeaf10b for floryn[9](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L9)0/hugo:0.128.2-ext-alpine-ci with digest floryn90/hugo@sha256:5075a37159ad14b93ba3c945eb0f40e57d739eb59a75c4159c17e7a5bc[10](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L10)8e8f ...
$ hugo
hugo: downloading modules …
hugo: collected modules in 14523 ms
Start building sites … 
hugo v0.128.2-de36c1a95d28595d8243fd8b891665b069ed0850+extended linux/amd64 BuildDate=2024-07-04T08:13:25Z VendorInfo=gohugoio
WARN  deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.Disqus.Shortname instead.
Total in 19965 ms
Error: error building site: POSTCSS: failed to transform "/scss/main.css" (text/css): Error: Loading PostCSS Plugin failed: Cannot find module 'autoprefixer'
Require stack:
- /tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/postcss.config.js
(@/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/postcss.config.js)
    at load (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/plugins.js:28:[11](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L11))
    at async Promise.all (index 0)
    at async plugins (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/plugins.js:57:[12](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L12))
    at async processResult (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/index.js:39:[14](https://gitlab.com/graphviz/graphviz.gitlab.io/-/jobs/7272252861#L14))
    at async Promise.all (index 0)
```

I wonder if this might not quite be fixed yet?

**Comment by floryn90** [comment]
I tested directly the image and the autoprefixer is available inside the image and into $PATH env variable

**Comment by mhansen** [comment]
OK, interesting, maybe this is a problem on our end.

**Comment by floryn90** [comment]
If the issue persists, please open another issue and I’ll take a look

**Comment by mhansen** [comment]
I hit 'rerun' again and it worked. The difference seems to be two different
SHAs for the same tag

FAILING: Using docker image
sha256:1b794749e1206f2afad19a491a950558d327584d5ae9aab4351641580eeaf10b for
floryn90/hugo:0.128.2-ext-alpine-ci with digest
***@***.***:5075a37159ad14b93ba3c945eb0f40e57d739eb59a75c4159c17e7a5bc108e8f
...

PASSING: Using docker image
sha256:db3ec8498a4ec649a16376de4956525525c49994d14f7439bb02ba4b83e3497d for
floryn90/hugo:0.128.2-ext-alpine-ci with digest
***@***.***:006301bab0bb3f435bb9abe3790c39be3554de974c3e3566ece8ad402f194c07
...
